### PR TITLE
Add TCP support for GELF

### PR DESCRIPTION
**Pull request by zsprackett**
Not final.  I'm just submitting this for review.  Still needs tests but it works and I want to make sure you're onboard.

### CODE REVIEW

**Comment by asm0dey** [comment]
:+1:

**Comment by zsprackett** [comment]
CA sent in today.

**Comment by lennartkoopmann** [comment]
Hey @zsprackett,

we unfortunately have a timing problem here. The IP holding entity has changed to Graylog, Inc and we need to adapt the CA. This might take us a few days and you'll have to re-issue it. Sorry about that.

Thanks,
Lennart

**Comment by craigw** [comment]
Hello all,

Thanks for your work on this - I'd really like to use it. Are there any updates you can share on the progress of getting this merged in?

Cheers,
Craig

**Comment by dennusb** [comment]
Is there any update?

**Comment by happysundar** [comment]
Ping!

**Comment by 00WCEnte** [comment]
+1

**Comment by lazureykis** [comment]
+1

**Comment by rlanore** [comment]
+1

**Comment by asm0dey** [comment]
:-1:

**Comment by andral** [comment]
+1

**Comment by daniilyar** [comment]
+1

**Comment by edefaria** [comment]
In order to use a patched logstash to send logs to a graylog2 with TCP/TLS support. I base on this patch and I add the TLS support by forking TCP classes. I have encountered some issue with dead socket and half-dead socket (socket timeout because you use an HA proxy behind the graylog2 server). So, I add some more reliable check (read the socket after writing to catch more exception). That is my first code in ruby, so it may probably better, but it does the job.

**Comment by evanccnyc** [comment]
Any update on when this might be merged in?

**Comment by vladimirsavenkov** [comment]
+1

**Comment by Mark2009** [comment]
+1

**Comment by zsprackett** [comment]
What do i need to sign to get this merged?

**Comment by dstockman** [comment]
@zsprackett Guessing it's this: https://www.graylog.org/contributing-to-graylog/

**Comment by zsprackett** [comment]
Resubmitted CLA

**Comment by dstockman** [comment]
Thanks! @zsprackett for President 2016!

**Comment by siawyoung** [comment]
I needed this quite urgently so I forked the current master and pulled @zsprackett's 3 commits in (TCP works quite smoothly btw, great job!)

https://github.com/siawyoung/gelf-rb

**Comment by edefaria** [comment]
You manage the TCP/UDP option by adding a default option protocol. So the gelf, add a protocol field by default with this patch (with 0 or 1 as value). 
This information is futile and I think it should not be added as a gelf field by default.

I also think that would be cleaner to move "module Protocol" for TCP definition from file "gelf.rb" to the begin of the file "ruby_sender.rb".

**Comment by adrianlyjak** [comment]
+1

**Comment by edefaria** [comment]
I add TLS support for TCP protocol based on your fork, I needed it to get a secure way to send from a logstash to a graylog2 server through Internet.
You do a great job for this code and it helps me a lot to undertake this objective.

My current fork with TLS/TCP support:
https://github.com/edefaria/gelf-rb

**Comment by siawyoung** [comment]
Any progress on this pull request?

**Comment by patricktjel** [comment]
+1

**Comment by zsprackett** [comment]
@lennartkoopmann anything we can do to get this merged?

**Comment by mvallerie** [comment]
+1

**Comment by kanny** [comment]
+1

**Comment by ggsenger** [comment]
+1 ... it's been almost two years ...

**Comment by kanny** [comment]
@lennartkoopmann @joschi Is there any blocks to merge this? We're using graylog by this gem and we need this feature for more reliability.

**Comment by claudekenni** [comment]
+1

**Comment by dstockman** [comment]
@lennartkoopmann @zsprackett Thank you! <3

**Comment by lennartkoopmann** [comment]
It is happening!! :)

**Comment by lennartkoopmann** [comment]
[Published on rubygems as v2.0.0](https://rubygems.org/gems/gelf)

**Comment by kanny** [comment]
Thank you!! :dizzy:

**Pull request merged**
